version: "4.1"
services:
  master:
    image: redis:7.0.4
    container_name: redis-master
    restart: always
    command: bash -c "redis-server --protected-mode no --slave-announce-ip 172.29.29.23 --slave-announce-port 6377 --requirepass 'redis'"
    ports:
      - 6377:6379
  slave1:
    image: redis:7.0.4
    container_name: redis-slave-1
    restart: always
    ports:
      - 6380:6379
    command:  bash -c "redis-server --protected-mode no --slaveof 172.29.29.23 6377 --slave-announce-ip 172.29.29.23 --slave-announce-port 6380 --requirepass 'redis' --masterauth 'redis'"

  slave2:
    image: redis:7.0.4
    container_name: redis-slave-2
    restart: always
    ports:
      - 6381:6379
    command: bash -c "redis-server --protected-mode no --slaveof 172.29.29.23 6377 --slave-announce-ip 172.29.29.23 --slave-announce-port 6381 --requirepass 'redis' --masterauth 'redis'"
